version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./mysql.env
    networks:
      - api
    healthcheck:
      test: "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"
      timeout: 20s
      interval: 2s
      retries: 10
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./dev.env
    networks:
      - api

volumes:
  db_data:

networks:
  api:
