# Generated by Django 3.2.8 on 2021-11-29 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20211126_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
