# Generated by Django 3.2.8 on 2021-11-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='fat',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
