# Generated by Django 3.2.8 on 2021-11-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_recipe_fat'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbohydrates',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
