# Generated by Django 3.2.8 on 2021-10-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20211017_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calo',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
