# Generated by Django 3.2.8 on 2021-11-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_courses_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='owner',
            new_name='teacher',
        ),
    ]
