# Generated by Django 3.2.8 on 2021-11-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_rename_owner_courses_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
