# Generated by Django 3.2.8 on 2021-11-29 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20211126_0134'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise', '0005_courses_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='menu.recipe')),
            ],
            options={
                'managed': True,
                'unique_together': {('recipe', 'user')},
            },
        ),
    ]
