# Generated by Django 3.2.8 on 2021-11-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_schedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
    ]
