# Generated by Django 3.2.8 on 2021-11-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_auto_20211129_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='eat_ad',
            field=models.CharField(choices=[('sang', 'sang'), ('trua', 'trua'), ('toi', 'toi'), ('them', 'them')], default='sang', max_length=20),
        ),
    ]
