# Generated by Django 3.2.8 on 2021-11-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0009_schedule_eat_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='eat_ad',
            new_name='eat_at',
        ),
    ]
