# Generated by Django 3.2.8 on 2021-11-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0010_rename_eat_ad_schedule_eat_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
